version: "3"
services:
  code-server:
    build: ./image
    volumes:
      - "./vscode_data/:/home/coder/vscode_data"
      - "./code_server/:/home/coder/.config/code-server"
      - "./share:/home/coder/share"
    ports:
      - "8080:9141"
    environment:
      - PASSWORD=test
      - PORT=9141
    restart: on-failure
